---
- hosts: staging
  tasks:

    # create folder for the app
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /home/{{ ansible_user_id }}/myapp
        state: directory
        mode: '0755'

    # make sure unzip is install
    - name: Update apt cache and make sure unzip is installed
      become: true
      apt:
        name: unzip
        update_cache: yes

    # unarchive the artifact from realase pipeline
    - name: Unarchive artifact
      ansible.builtin.unarchive:
        src: /home/{{ ansible_user_id }}/57.zip
        dest: /home/{{ ansible_user_id }}/myapp
        remote_src: yes
        
    # download nodeJs repo
    - name: Add nodejs repository
      shell: curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
      args:
        warn: no
    # install nodeJS version 14
    - name: Install nodejs
      become: yes
      apt:
        update_cache: yes
        name: nodejs
        state: present
